# Generated by Django 4.2.3 on 2023-07-20 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_profile_img_alter_user_profile_number'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(choices=[('size', 'size'), ('color', 'color')], max_length=100),
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('product_name', models.CharField(max_length=100)),
                ('unit', models.IntegerField(default='1')),
                ('unit_total', models.DecimalField(decimal_places=2, max_digits=20)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('color', 'color')], max_length=200)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.inventory')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user_profile')),
            ],
        ),
    ]
