# Generated by Django 4.2.3 on 2023-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_attribute_description_alter_attribute_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('delivered', 'Delivered')], default='Placed', max_length=200),
        ),
    ]
