# Generated by Django 4.2.3 on 2023-07-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_order_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.IntegerField(null=True),
        ),
    ]
