# Generated by Django 4.2.3 on 2023-07-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('on the way', 'on the way'), ('delivered', 'Delivered')], default='Placed', max_length=200),
        ),
    ]
